#lanuage
language: python
#version
python:
  - "3.6"

env: - NOSE_REDNOSE=1
# command to install dependencies
install:
  - pip install
  - pip install -r requirements.txt
  - pip install rednose
  - pip install coveralls

services:
  - postgresql

# command to run tests
script: nosetests --exe -v --with-coverage --cover-package=flights

after_success: coveralls
