new_booking = dict(
                flight_name="Flight No 3",
                seat_number="1FL",
                payment="200000")
blank_flight = dict(
                flight_name="",
                seat_number="1FL",
                payment="200000")
blank_seat = dict(
                flight_name="Flight No 3",
                seat_number="",
                payment="200000")
no_payment = dict(
                flight_name="Flight No 3",
                seat_number="1FL",
                payment="")

blank_flight_key = dict(
                seat_number="1FL",
                payment="200000")
blank_seat_key = dict(
                flight_name="Flight No 3",
                payment="200000")
blank_payment_key = dict(
                flight_name="Flight No 3",
                seat_number="1FL")
another_booking = dict(
                flight_name="Flight No 3",
                seat_number="1BO",
                payment="200000")